apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "elasticsearch.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "elasticsearch.fullname" . }}-headless
  {{- if not .Values.elasticsearch.autoscaling.enabled }}
  replicas: {{ .Values.elasticsearch.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "elasticsearch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "elasticsearch.labels" . | nindent 8 }}
    spec:
      {{- with .Values.elasticsearch.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.enablerNodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.enablerNodeSelector }}
        {{- with .Values.elasticsearch.nodeSelector }}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.elasticsearch.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.elasticsearch.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.elasticsearch.podSecurityContext | nindent 8 }}
      containers:
        - name: elasticsearch
          securityContext:
            {{- toYaml .Values.elasticsearch.securityContext | nindent 12 }}
          image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.elasticsearch.image.pullPolicy }}
          ports:
            - name: elasticport
              containerPort: {{ .Values.elasticsearch.service.ports.elasticport.containerPort }}
              protocol: {{ .Values.elasticsearch.service.ports.elasticport.protocol }}
          resources:
            {{- toYaml .Values.elasticsearch.resources | nindent 12 }}
          {{- with .Values.elasticsearch.envVars }}
          env:
            - name: http.host
              value: {{ .httpHost | quote }}          
            - name: discovery.type
              value: {{ .discoveryType | quote }}
            - name: cluster.name
              value: {{ .clusterName | quote }}
            - name: script.allowed_types
              value: {{ .scriptAllowedTypes | quote }}
            - name: thread_pool.search.queue_size
              value: {{ .threadPoolSearchQueueSize | quote }}
            - name: thread_pool.write.queue_size
              value: {{ .threadPoolWriteQueueSize | quote }}
            - name: gateway.recover_after_nodes
              value: {{ .gatewayRecoverAfterNodes | quote }}
            - name: xpack.security.enabled
              value: {{ .xpackSecurityEnabled | quote }}
            - name: bootstrap.memory_lock
              value: {{ .bootstrapMemoryLock | quote }}
            - name: ES_JAVA_OPTS
              value: {{ .esJavaOpts | quote }}
          {{- end }}
          volumeMounts:
            {{- if .Values.elasticsearch.persistence.enabled }}
            - name: data
              mountPath: /usr/share/elasticsearch/data
            {{- end }}
      {{- with .Values.elasticsearch.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
  {{- if and .Values.elasticsearch.persistence.enabled .Values.elasticsearch.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ tpl .Values.elasticsearch.persistence.existingClaim $ }}
  {{- else if not .Values.elasticsearch.persistence.enabled }}
        - name: data
          emptyDir: {}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
        {{- range .Values.elasticsearch.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.elasticsearch.persistence.size | quote }}
  {{- end }}
