apiVersion: v1
kind: Service
metadata:
  name: {{ include "wazuh.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.globalService }}
    {{- include "globalServiceAnnotations" . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.wazuh.service.type }}
  ports:
    - name: agentport1
      port: {{ .Values.wazuh.service.ports.agentport1.port }}
      targetPort: {{ .Values.wazuh.service.ports.agentport1.targetPort }}
      protocol: {{ .Values.wazuh.service.ports.agentport1.protocol }}
      {{- if and (or (eq .Values.wazuh.service.type "NodePort") (eq .Values.wazuh.service.type "LoadBalancer")) (not (empty .Values.wazuh.service.ports.agentport1.nodePort)) }}
      nodePort: {{ .Values.wazuh.service.ports.agentport1.nodePort }}
      {{- end }}
    - name: agentport2
      port: {{ .Values.wazuh.service.ports.agentport2.port }}
      targetPort: {{ .Values.wazuh.service.ports.agentport2.targetPort }}
      protocol: {{ .Values.wazuh.service.ports.agentport2.protocol }}
      {{- if and (or (eq .Values.wazuh.service.type "NodePort") (eq .Values.wazuh.service.type "LoadBalancer")) (not (empty .Values.wazuh.service.ports.agentport2.nodePort)) }}
      nodePort: {{ .Values.wazuh.service.ports.agentport2.nodePort }}
      {{- end }}
    - name: agentport3
      port: {{ .Values.wazuh.service.ports.agentport3.port }}
      targetPort: {{ .Values.wazuh.service.ports.agentport3.targetPort }}
      protocol: {{ .Values.wazuh.service.ports.agentport3.protocol }}
      {{- if and (or (eq .Values.wazuh.service.type "NodePort") (eq .Values.wazuh.service.type "LoadBalancer")) (not (empty .Values.wazuh.service.ports.agentport3.nodePort)) }}
      nodePort: {{ .Values.wazuh.service.ports.agentport3.nodePort }}
      {{- end }}
    - name: api
      port: {{ .Values.wazuh.service.ports.api.port }}
      targetPort: {{ .Values.wazuh.service.ports.api.targetPort }}
      protocol: {{ .Values.wazuh.service.ports.api.protocol }}
      {{- if and (or (eq .Values.wazuh.service.type "NodePort") (eq .Values.wazuh.service.type "LoadBalancer")) (not (empty .Values.wazuh.service.ports.api.nodePort)) }}
      nodePort: {{ .Values.wazuh.service.ports.api.nodePort }}
      {{- end }}
  selector:
    {{- include "wazuh.selectorLabels" . | nindent 4 }}
