apiVersion: v1
kind: Service
metadata:
  name: {{ include "kibana.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kibana.service.type }}
  ports:
    - name: kibanaport
      port: {{ .Values.kibana.service.ports.kibanaport.port }}
      targetPort: {{ .Values.kibana.service.ports.kibanaport.targetPort }}
      protocol: {{ .Values.kibana.service.ports.kibanaport.protocol }}
      {{- if and (or (eq .Values.kibana.service.type "NodePort") (eq .Values.kibana.service.type "LoadBalancer")) (not (empty .Values.kibana.service.ports.kibanaport.nodePort)) }}
      nodePort: {{ .Values.kibana.service.ports.kibanaport.nodePort }}
      {{- end }}
  selector:
    {{- include "kibana.selectorLabels" . | nindent 4 }}
