apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend
  name: backend
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
  selector:
    service: backend
status:
  loadBalancer: {}
