apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: cortex-claim2
  name: cortex-claim2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
