apiVersion: v1
kind: Service
metadata:
  labels:
    service: cortex
  name: cortex
spec:
  ports:
    - name: "9001"
      port: 9001
      targetPort: 9001
  selector:
    service: cortex
status:
  loadBalancer: {}
