apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      service: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: database
    spec:
      containers:
        - image: frikky/shuffle:database
          name: shuffle-database
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - mountPath: /etc/shuffle
              name: database-claim0
      hostname: shuffle-database
      restartPolicy: Always
      volumes:
        - name: database-claim0
          persistentVolumeClaim:
            claimName: database-claim0
status: {}
