apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: database-claim0
  name: database-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
