apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: elasticsearch-claim1
  name: elasticsearch-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
