apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
  strategy: {}
  template:
    metadata:
      labels:
        service: frontend
    spec:
      containers:
        - env:
            - name: BACKEND_HOSTNAME
              value: shuffle-backend
          image: ghcr.io/frikky/shuffle-frontend:0.8.64
          name: shuffle-frontend
          ports:
            - containerPort: 80
            - containerPort: 443
          resources: {}
      hostname: shuffle-frontend
      restartPolicy: Always
status: {}
