apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 80
    - name: "3443"
      port: 3443
      targetPort: 443
  selector:
    service: frontend
status:
  loadBalancer: {}
