apiVersion: v1
kind: Service
metadata:
  labels:
    service: misp
  name: misp
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
  selector:
    service: misp
status:
  loadBalancer: {}
