apiVersion: v1
kind: Service
metadata:
  labels:
    service: thehive
  name: thehive
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    service: thehive
status:
  loadBalancer: {}
