apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: elasticsearch-logs
  name: elasticsearch-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
