apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      service: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: elasticsearch
    spec:
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: cluster.name
              value: wazuh-cluster
            - name: discovery.type
              value: single-node
            - name: network.host
              value: 0.0.0.0
          image: amazon/opendistro-for-elasticsearch:1.13.2
          name: elasticsearch
          ports:
            - containerPort: 9200
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-data
            - mountPath: /usr/share/elasticsearch/logs
              name: elasticsearch-logs
      hostname: elasticsearch
      restartPolicy: Always
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: elasticsearch-data
        - name: elasticsearch-logs
          persistentVolumeClaim:
            claimName: elasticsearch-logs
status: {}
