apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: filebeat-etc
  name: filebeat-etc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
