apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: ossec-active-response
  name: ossec-active-response
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
