apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: ossec-wodles
  name: ossec-wodles
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
