apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: ossec-agentless
  name: ossec-agentless
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
