apiVersion: v1
kind: Service
metadata:
  name: {{ include "cortex.svc.headless" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "cortex.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: cortexport
      port: {{ .Values.cortex.service.ports.cortexport.port }}
      targetPort: {{ .Values.cortex.service.ports.cortexport.targetPort }}
      protocol: {{ .Values.cortex.service.ports.cortexport.protocol }}
  selector:
    {{- include "cortex.selectorLabels" . | nindent 4 }}