apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.svc.headless" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: api
      port: {{ .Values.elasticsearch.service.ports.api.port }}
      targetPort: {{ .Values.elasticsearch.service.ports.api.targetPort }}
      protocol: {{ .Values.elasticsearch.service.ports.api.protocol }}
  selector:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}